// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GameFinale.Models
{
    public partial class Carrello
    {
        public Carrello()
        {
            Utentes = new HashSet<Utente>();
        }

        public int IdCarrello { get; set; }
        public int? QuantitaTotale { get; set; }
        public string Prezzo { get; set; }
        public int? IdProdotto { get; set; }

        public virtual Prodotto IdProdottoNavigation { get; set; }
        public virtual ICollection<Utente> Utentes { get; set; }
    }
}