// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GameFinale.Models
{
    public partial class Negozio
    {
        private List<Prodotto> prodottiDisponibili = new List<Prodotto>();
        public int IdNegozio { get; set; }
        public int? IdProdotto { get; set; }
        public string NomeProdotto { get; set; }



        public virtual Prodotto IdProdottoNavigation { get; set; }
    }
}