// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GameFinale.Models
{
    public partial class Prodotto
    {
        public Prodotto()
        {
            Carrellos = new HashSet<Carrello>();
        }

        public int IdProdotto { get; set; }
        public string Nome { get; set; }
        public int? Prezzo { get; set; }
        public int? Quantita { get; set; }

        public virtual ICollection<Carrello> Carrellos { get; set; }
    }
}