// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GameFinale.Models
{
    public partial class Utente
    {
        public int IdUtente { get; set; }
        public string NomeUtente { get; set; }
        public int IdCarrello { get; set; }

        public virtual Carrello IdCarrelloNavigation { get; set; }
    }
}